### ISSUE TITLE
Can not download dictionary using the python

### ISSUE THREAD

**Issue by googoodalls** [nickcheng/NCChineseConverter#1]
/Users/hello/NCChineseConverter/tools
Hellos-MBP:tools steven$ python dictgenerator.py
Downloading ZhConversion.php ...
Download accomplished.
Parsing wiki source...
{}
[{}]
Traceback (most recent call last):
  File "dictgenerator.py", line 69, in <module>
    main()
  File "dictgenerator.py", line 66, in main
    makeDictFile()
  File "dictgenerator.py", line 43, in makeDictFile
    [dic_TW, dic_HK, dic_SG, dic_CN] = mdic()
  File "dictgenerator.py", line 27, in mdic
    name[3].update(name[1]) # 简繁通用转换规则(zh2Hant)加上台湾区域用法(zh2TW)
IndexError: list index out of range
Hellos-MBP:tools hello$ 

Could you help me?

**Comment by nickcheng** [comment]
I use `ZhConversion.php` in MediaWiki to be the source of the dictionary.
Unfortunately, this file seems be removed or moved to another place. So you can't use the tool for now.
But I have placed a generated dictionary in the folder `Example/Resource`. You can use it if you still need.
